'use client'

import { useEffect, useState } from 'react'
import { api } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Loader2, Eye, EyeOff, CheckCircle2, AlertCircle } from 'lucide-react'

// Public page reached from a one-time set-password link (generated by an admin
// when creating a user). The token is read from the query string client-side so
// the page needs no server-side auth.
export default function SetPasswordPage() {
  const [token, setToken] = useState<string | null>(null)
  const [ready, setReady] = useState(false)
  const [password, setPassword] = useState('')
  const [confirm, setConfirm] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [done, setDone] = useState(false)

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    setToken(params.get('token'))
    setReady(true)
  }, [])

  const passwordsMatch = confirm.length > 0 && password === confirm
  const canSubmit = password.length >= 6 && passwordsMatch && !loading

  async function submit(e: React.FormEvent) {
    e.preventDefault()
    setError('')
    if (password.length < 6) {
      setError('Password must be at least 6 characters')
      return
    }
    if (password !== confirm) {
      setError('Passwords do not match')
      return
    }
    if (!token) {
      setError('This link is invalid or has expired')
      return
    }
    setLoading(true)
    try {
      await api.setPassword(token, password)
      setDone(true)
    } catch (err: any) {
      setError(err.message || 'Failed to set password')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-zinc-50 dark:bg-zinc-950 p-4">
      <div className="w-full max-w-md">
        <Card className="border-zinc-200 dark:border-zinc-800 shadow-sm">
          {!ready ? (
            <CardContent className="py-16 text-center">
              <Loader2 className="w-6 h-6 mx-auto animate-spin text-zinc-400" />
            </CardContent>
          ) : !token ? (
            <CardContent className="py-12 text-center">
              <AlertCircle className="w-10 h-10 mx-auto mb-3 text-red-500" />
              <CardTitle className="text-lg mb-1">Invalid link</CardTitle>
              <p className="text-sm text-zinc-500 mb-4">This set-password link is missing its token. Ask an admin to send a new one.</p>
              <Button asChild variant="outline"><a href="/">Back to home</a></Button>
            </CardContent>
          ) : done ? (
            <CardContent className="py-12 text-center">
              <CheckCircle2 className="w-10 h-10 mx-auto mb-3 text-emerald-500" />
              <CardTitle className="text-lg mb-1">Password set</CardTitle>
              <p className="text-sm text-zinc-500 mb-4">You can now sign in with your email and new password.</p>
              <Button asChild className="bg-emerald-600 hover:bg-emerald-700 text-white"><a href="/?signin=1">Go to sign in</a></Button>
            </CardContent>
          ) : (
            <>
              <CardHeader>
                <CardTitle className="text-xl">Set your password</CardTitle>
                <CardDescription>Choose a password for your account.</CardDescription>
              </CardHeader>
              <CardContent>
                <form className="space-y-4" onSubmit={submit}>
                  <div className="space-y-1.5">
                    <Label htmlFor="new-password">New password</Label>
                    <div className="relative">
                      <Input
                        id="new-password"
                        type={showPassword ? 'text' : 'password'}
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        placeholder="min 6 characters"
                        autoComplete="new-password"
                        autoFocus
                        className="pr-10"
                      />
                      <button
                        type="button"
                        onClick={() => setShowPassword(!showPassword)}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200"
                        aria-label={showPassword ? 'Hide password' : 'Show password'}
                      >
                        {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                    {password.length > 0 && password.length < 6 && (
                      <p className="text-xs text-red-500">Password must be at least 6 characters</p>
                    )}
                  </div>

                  <div className="space-y-1.5">
                    <Label htmlFor="confirm-password">Confirm password</Label>
                    <Input
                      id="confirm-password"
                      type={showPassword ? 'text' : 'password'}
                      value={confirm}
                      onChange={(e) => setConfirm(e.target.value)}
                      placeholder="••••••••"
                      autoComplete="new-password"
                    />
                    {confirm.length > 0 && !passwordsMatch && (
                      <p className="text-xs text-red-500">Passwords do not match</p>
                    )}
                  </div>

                  {error && <p className="text-sm text-red-500">{error}</p>}

                  <Button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white" disabled={!canSubmit}>
                    {loading ? <><Loader2 className="w-4 h-4 animate-spin mr-1" /> Saving…</> : 'Set password'}
                  </Button>
                </form>
              </CardContent>
            </>
          )}
        </Card>
      </div>
    </div>
  )
}
