import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { hashPassword } from '@/lib/auth'
import { verifyResetToken } from '@/lib/password'
import { logActivity, getRequestIp, getRequestUserAgent, generateReferenceId } from '@/lib/activity-log'
import { setPasswordSchema, parseWith } from '@/lib/validation'
import { rateLimit, rateLimitResponse, clientIp } from '@/lib/rate-limit'

// POST /api/auth/set-password
//
// Consumes a one-time set-password link (generated by an admin when creating a
// user, or by the forgot-password flow once SMTP is wired up). The token is
// signed with the user's current sessionVersion; consuming it bumps that
// version, which makes the link single-use and signs the user out everywhere.
export async function POST(req: NextRequest) {
  try {
    const limit = rateLimit({
      scope: 'auth:set-password:ip',
      identifier: clientIp(req),
      limit: 20,
      windowMs: 60 * 60 * 1000,
    })
    if (!limit.ok) return rateLimitResponse(limit)

    const body = await req.json().catch(() => null)
    const parsed = parseWith(setPasswordSchema, body)
    if (!parsed.ok) {
      return NextResponse.json({ error: parsed.error }, { status: 400 })
    }

    const payload = verifyResetToken(parsed.data.token)
    if (!payload) {
      return NextResponse.json({ error: 'This link is invalid or has expired' }, { status: 400 })
    }

    const user = await db.user.findUnique({
      where: { id: payload.sub },
      select: { id: true, email: true, sessionVersion: true, status: true },
    })
    if (!user || user.sessionVersion !== payload.v) {
      return NextResponse.json({ error: 'This link is invalid or has already been used' }, { status: 400 })
    }
    if (user.status === 'BANNED') {
      return NextResponse.json({ error: 'This account has been suspended' }, { status: 403 })
    }

    await db.user.update({
      where: { id: user.id },
      data: {
        passwordHash: hashPassword(parsed.data.password),
        // Bump so the link can't be replayed and any stolen session is evicted.
        sessionVersion: { increment: 1 },
      },
    })

    await logActivity({
      userId: user.id,
      userEmail: user.email,
      actionType: 'PROFILE_CHANGED',
      action: 'Password set',
      description: `Password set via one-time link for ${user.email}`,
      status: 'SUCCESS',
      referenceId: generateReferenceId('LOG'),
      ipAddress: getRequestIp(req),
      userAgent: getRequestUserAgent(req),
    })

    return NextResponse.json({ ok: true })
  } catch {
    return NextResponse.json({ error: 'Failed to set password' }, { status: 500 })
  }
}
